apiVersion: v1
kind: Template
labels:
  template: buildconfig-template
metadata:
  annotations:
    description: Template for creating a build configuration for binary S2I builds.
  creationTimestamp: null
  name: buildconfig-template
parameters:
  - name: APP_NAME
    displayName: Application Name
    required: true
    description: The name assigned to the application.
  - name: APP_VERSION
    displayName: Application Version
    required: true
    description: The version assigned to the application.
  - name: APP_NAMESPACE
    displayName: Application namespace
    required: true
    description: The name of the assigned namespace.
  - name: GENERIC_TRIGGER_SECRET_VALUE
    generate: expression
    from: "[A-Za-z0-9]{20}"
    required: true
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: buildconfig-template
    creationTimestamp: null
    labels:
      component: ${APP_NAME}
      group: ${APP_NAMESPACE}
      app: ${APP_NAME}
      provider: s2i
      version: ${APP_VERSION}
    name: ${APP_NAME}
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: ${APP_NAME}:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      binary: {}
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: fis-java-openshift:2.0
          namespace: jboss-fuse-6
      type: Source
    triggers:
    - generic:
        secret: ${GENERIC_TRIGGER_SECRET_VALUE}
      type: Generic
  status:
    lastVersion: 0
