apiVersion: v1
kind: Template
labels: {}
metadata:
  annotations:
    description: This template deploys an image stream to the defined namespace
    iconClass: icon-java
  labels: {}
  name: imagestream-template
parameters:
  - name: APP_NAME
    displayName: Application Name
    required: true
    description: The name assigned to the application.
  - name: APP_VERSION
    displayName: Application Version
    required: true
    description: The application version.
  - name: APP_NAMESPACE
    displayName: Application namespace
    required: true
    description: The name of the assigned namespace.
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      annotations:
        openshift.io/generated-by: imagestream-template
      name: ${APP_NAME}
      creationTimestamp: null
      labels:
        component: ${APP_NAME}
        group: ${APP_NAMESPACE}
        app: ${APP_NAME}
        provider: s2i
        version: ${APP_VERSION}
    spec: {}